### ISSUE TITLE
Multibrowser support

### ISSUE THREAD

**Issue by snaggen** [stoffu/xmrto-lens#14]
It would be nice to have this available in Firefox also... and since webextensions are getting standardized, this should be possible.... not sure how much work it is. Found this guide on the www: https://www.smashingmagazine.com/2017/04/browser-extension-edge-chrome-firefox-opera-brave-vivaldi/

**Comment by stoffu** [comment]
Indeed, maybe I'll work on it if there's enough demand. FWIW Opera can run the exact same Chrome extension using this: https://addons.opera.com/en/extensions/details/install-chrome-extensions/

If someone else can take on this task, it'd be great :)

**Comment by snaggen** [comment]
Ok, then I will demand this! 😄

**Comment by stoffu** [comment]
Turns out that the code was already almost fully compatible in Firefox.
Now available on https://addons.mozilla.org/en-US/firefox/addon/xmr-to-lens/
